### ISSUE TITLE
Unable to build on cross platform

### ISSUE THREAD

**Issue by melkir** [RustNSparks/pusher-http-rust#1]
Trying to compile my project using [cross-compiling](https://github.com/sodiumoxide/sodiumoxide#cross-compiling) on MacOS via [cross](https://github.com/cross-rs/cross), the process is failing for the target `armv7-unknown-linux-gnueabihf` due to the following error from sodiumoxide.

> Could not find directory of OpenSSL installation, and this `-sys` crate cannot proceed without this knowledge.

Could we make `rustls` optional?

**Comment by countradooku** [comment]
i will see what i can do

**Comment by countradooku** [comment]
Thank you for reporting this issue! You're absolutely right - the current dependencies make cross-compilation difficult. The issue is actually twofold:

1. **sodiumoxide** requires native libsodium compilation
2. **reqwest** is using `native-tls` which requires OpenSSL on Linux

## Proposed Solution

I've prepared a comprehensive solution that addresses both issues:

### 1. Make TLS Backend Configurable

```toml
[features]
default = ["rustls-tls", "encryption"]
# TLS backends (mutually exclusive)
native-tls = ["reqwest/native-tls"]
rustls-tls = ["reqwest/rustls-tls"]
```

This makes `rustls` the default, which is pure Rust and doesn't require OpenSSL.

### 2. Make Encryption Optional

```toml
# Optional encryption support
encryption = ["sodiumoxide", "aes-gcm", "chacha20poly1305"]
```

This allows users to disable encryption entirely if they don't need encrypted channels.

### 3. Provide Pure-Rust Encryption Alternative

When `sodiumoxide` is not available (or when cross-compiling), the library can fall back to using `chacha20poly1305`, which is a pure-Rust implementation of the same algorithm used in TLS 1.3.

## Usage After Changes

For cross-compilation, you would use the default features:

```toml
[dependencies]
pushers = "1.3.0"
```

Then cross-compilation should work:

```bash
cross build --target armv7-unknown-linux-gnueabihf --release
```

If you don't need encryption at all:

```toml
[dependencies]
pushers = { version = "1.3.0", default-features = false, features = ["rustls-tls"] }
```

## Benefits

- ✅ No OpenSSL dependency by default
- ✅ Works with `cross` out of the box  
- ✅ Maintains backward compatibility
- ✅ Optional encryption for lighter builds
- ✅ Pure-Rust alternative for crypto

Would this solution work for your use case? I'm happy to prepare a PR with these changes if you'd like to test it.
